# Легкий вариант RAG без ChromaDB (только для тестирования)
# Используйте этот файл если размер Docker образа критичен

dependencies = [
    "aiogram>=3.13.0",
    "python-dotenv>=1.0.0",
    "openai>=1.0.0",
    "requests>=2.31.0",
    # Минимальные RAG зависимости
    "PyPDF2>=3.0.0",
    "numpy>=1.21.0",
    # Легкая модель эмбеддингов (без ChromaDB)
    "scikit-learn>=1.0.0",
]
